import { cp, mkdir, readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
const root = resolve(import.meta.dirname, '..'); const dist = resolve(root, 'dist'); await mkdir(dist, { recursive: true });
await cp(resolve(root, 'src', 'search-attachment-menu.mjs'), resolve(dist, 'search-attachment-menu.mjs'));
await cp(resolve(root, 'src', 'search-result-cache.mjs'), resolve(dist, 'search-result-cache.mjs'));
for (const file of ['index.html', 'styles.css', 'viewport-shell.css', 'chat-shell.css', 'image-preview.css', 'modal-layer-owner.mjs', 'p8-inspect.css', 'desktop-transcription-page.css', 'desktop-reminders-page.css', 'app.mjs', 'cloud-read-feedback.mjs', 'answer-information.mjs', 'composer-size.mjs', 'android-action-icons.mjs', 'chat-shell.mjs', 'conversation-message-order.mjs', 'conversation-long-press.mjs', 'conversation-lifecycle-view.mjs', 'conversation-find-interaction.mjs', 'selected-conversation-continuation.mjs', 'local-data-view.mjs', 'desktop-search-page.mjs', 'desktop-attachment-preview-owner.mjs', 'image-preview-navigation.mjs', 'search-result-anchor.mjs', 'desktop-theme-owner.mjs', 'cloud-conversation-list-merge.mjs', 'cloud-conversation-open-route.mjs', 'c08-search-preview-fixture.mjs', 'c09-reminder-preview-fixture.mjs', 'c10-transcription-preview-fixture.mjs', 'c12-model-network-preview-fixture.mjs', 'c13-conversation-lifecycle-preview-fixture.mjs', 'c14-local-data-preview-fixture.mjs', 'c15-workspace-preview-fixture.mjs', 'c16-theme-matrix-fixture.mjs', 'workspace-view.mjs', 'desktop-transcription-page.mjs', 'desktop-reminders-page.mjs', 'safe-markdown.mjs', 'code-syntax.mjs', 'source-link-presentation.mjs', 'icon-source.mjs', 'desktop-parity-preferences.mjs', 'desktop-cost-estimator.mjs', 'android-settings-shell.mjs', 'p8-inspect.mjs', 'pwa-boundaries.mjs', 'recycle-confirmation.mjs', 'reminder-notification-routing.mjs']) await cp(resolve(root, 'src', file), resolve(dist, file));
await cp(resolve(root, '../app/src/main/res/drawable-nodpi/nanfeng_ai_icon_foreground_image.png'), resolve(dist, 'nanfeng-ai-icon.png'));
const report = JSON.parse((await readFile(resolve(root, '../protocol/fixtures/nfai.exchange.v1.golden.json'), 'utf8'))); await writeFile(resolve(dist, 'fixture-summary.json'), JSON.stringify({ format: report.format, version: report.version, semanticHash: report.export.semanticHash }));
console.log(`desktop static spike built: ${dist}`);
