"""Convert unmodified AndroidX Rounded path commands to SVG (Apache-2.0)."""
import json,re,sys,zipfile
from pathlib import Path
mapping={'pushPin':'PushPin','pushPinOff':'PushPin','bookmark':'Bookmark','bookmarkBorder':'BookmarkBorder','cloudUpload':'CloudUpload','visibility':'Visibility','share':'Share','search':'Search','archive':'Archive','restore':'Unarchive','trash':'DeleteOutline','edit':'Edit','info':'Info','close':'Close','check':'Check','plus':'Add','moreVertical':'MoreVert','chevronRight':'ChevronRight','chevronLeft':'ChevronLeft'}
commands={'moveTo':'M','moveToRelative':'m','lineTo':'L','lineToRelative':'l','horizontalLineTo':'H','horizontalLineToRelative':'h','verticalLineTo':'V','verticalLineToRelative':'v','curveTo':'C','curveToRelative':'c','reflectiveCurveTo':'S','reflectiveCurveToRelative':'s','quadTo':'Q','quadToRelative':'q','reflectiveQuadTo':'T','reflectiveQuadToRelative':'t','arcTo':'A','arcToRelative':'a','close':'Z'}
archives=[zipfile.ZipFile(p) for p in sys.argv[1:]]
result={}
for key,name in mapping.items():
 entry=f'commonMain/androidx/compose/material/icons/rounded/{name}.kt'
 text=next(z.read(entry).decode() for z in archives if entry in z.namelist())
 paths=[]
 for options,body in re.findall(r'materialPath(?:\((.*?)\))?\s*\{(.*?)\n\s*\}',text,re.S):
  pieces=[]
  for cmd,args in re.findall(r'(\w+)\(([^()]*)\)',body):
   if cmd not in commands:raise ValueError(cmd)
   args=args.replace('f','').replace('true','1').replace('false','0').replace(',',' ')
   pieces.append(commands[cmd]+args)
  paths.append('<path fill="currentColor" stroke="none" fill-rule="'+('evenodd' if 'EvenOdd' in options else 'nonzero')+'" d="'+' '.join(pieces)+'"/>')
 if not paths: raise ValueError(name)
 result[key]=''.join(paths)
Path('desktop/src/android-action-icons.mjs').write_text('// AndroidX Material Rounded original paths; Apache-2.0. Generated by sync-android-action-icons.py.\nexport const androidActionIcons = Object.freeze('+json.dumps(result,ensure_ascii=False,indent=2)+');\n')
