#!/usr/bin/env python3
"""Offline static audit for the versioned 南枫 AI launcher master and its packages.

This intentionally decodes only the non-interlaced RGB/RGBA PNGs generated by
the delivery flow.  It never talks to a device or claims Launcher/Dock visual
acceptance; it proves the source-to-package asset chain and geometric fidelity.
"""

from __future__ import annotations

import argparse
import hashlib
import struct
import sys
import zlib
from pathlib import Path


PNG_SIGNATURE = b"\x89PNG\r\n\x1a\n"


def read_png(path: Path) -> tuple[int, int, int, bytes]:
    raw = path.read_bytes()
    if not raw.startswith(PNG_SIGNATURE):
        raise ValueError(f"not a PNG: {path}")
    offset, payload, width, height, color_type = 8, [], None, None, None
    while offset < len(raw):
        length = struct.unpack(">I", raw[offset:offset + 4])[0]
        kind = raw[offset + 4:offset + 8]
        chunk = raw[offset + 8:offset + 8 + length]
        offset += 12 + length
        if kind == b"IHDR":
            width, height, bit_depth, color_type, compression, filter_type, interlace = struct.unpack(">IIBBBBB", chunk)
            if bit_depth != 8 or color_type not in (2, 6) or compression or filter_type or interlace:
                raise ValueError(f"unsupported PNG encoding: {path}")
        elif kind == b"IDAT":
            payload.append(chunk)
        elif kind == b"IEND":
            break
    if width is None or height is None:
        raise ValueError(f"missing IHDR: {path}")
    channels = 4 if color_type == 6 else 3
    scan = zlib.decompress(b"".join(payload))
    stride = width * channels
    rows, pos, prior = [], 0, bytearray(stride)
    for _ in range(height):
        mode, row = scan[pos], bytearray(scan[pos + 1:pos + 1 + stride])
        pos += stride + 1
        for i, value in enumerate(row):
            left = row[i - channels] if i >= channels else 0
            up = prior[i]
            up_left = prior[i - channels] if i >= channels else 0
            if mode == 1:
                row[i] = (value + left) & 0xFF
            elif mode == 2:
                row[i] = (value + up) & 0xFF
            elif mode == 3:
                row[i] = (value + ((left + up) // 2)) & 0xFF
            elif mode == 4:
                p, pa, pb, pc = left + up - up_left, 0, 0, 0
                pa, pb, pc = abs(p - left), abs(p - up), abs(p - up_left)
                row[i] = (value + (left if pa <= pb and pa <= pc else up if pb <= pc else up_left)) & 0xFF
            elif mode != 0:
                raise ValueError(f"unsupported filter: {path}")
        rows.append(bytes(row))
        prior = row
    return width, height, channels, b"".join(rows)


def visible_bounds(path: Path) -> tuple[int, int, int, int, int, int]:
    width, height, channels, pixels = read_png(path)
    xs, ys = [], []
    for y in range(height):
        for x in range(width):
            i = (y * width + x) * channels
            rgb = pixels[i:i + 3]
            alpha = pixels[i + 3] if channels == 4 else 255
            if alpha and rgb != b"\xff\xff\xff":
                xs.append(x)
                ys.append(y)
    if not xs:
        raise ValueError(f"no non-white subject pixels: {path}")
    # The user master can contain its own off-white material or baked shadow at an
    # edge.  Fidelity means recording it, never normalising those pixels to #FFFFFF.
    return min(xs), min(ys), max(xs), max(ys), width, height


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def require_file(root: Path, relative: str) -> None:
    if not (root / relative).is_file():
        raise ValueError(f"missing packaged icon input: {relative}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--candidate", type=Path, required=True)
    parser.add_argument("--expected-scale", type=float, required=True)
    parser.add_argument("--android-root", type=Path, default=Path("app"))
    parser.add_argument("--desktop-root", type=Path, default=Path("desktop/src-tauri"))
    args = parser.parse_args()
    source = visible_bounds(args.source)
    candidate = visible_bounds(args.candidate)
    source_w, source_h = source[2] - source[0] + 1, source[3] - source[1] + 1
    candidate_w, candidate_h = candidate[2] - candidate[0] + 1, candidate[3] - candidate[1] + 1
    ratio_w, ratio_h = candidate_w / source_w, candidate_h / source_h
    if abs(ratio_w - args.expected_scale) > 0.012 or abs(ratio_h - args.expected_scale) > 0.012:
        raise ValueError(f"subject scale mismatch: got {ratio_w:.4f}×/{ratio_h:.4f}×, expected {args.expected_scale:.2f}×")
    root = args.android_root
    manifest = (root / "src/main/AndroidManifest.xml").read_text(encoding="utf-8")
    if 'android:icon="@mipmap/ic_launcher"' not in manifest or 'android:roundIcon="@mipmap/ic_launcher_round"' not in manifest:
        raise ValueError("Manifest icon and roundIcon must share launcher resources")
    for relative in (
        "src/main/res/mipmap-anydpi-v26/ic_launcher.xml",
        "src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml",
        "src/main/res/drawable/nanfeng_ai_icon_background.xml",
        "src/main/res/drawable/nanfeng_ai_icon_foreground.xml",
        "src/main/res/drawable-nodpi/nanfeng_ai_icon_foreground_image.png",
    ):
        require_file(root, relative)
    for density in ("mdpi", "hdpi", "xhdpi", "xxhdpi", "xxxhdpi"):
        for name in ("ic_launcher.png", "ic_launcher_round.png"):
            require_file(root, f"src/main/res/mipmap-{density}/{name}")
    launcher = (root / "src/main/res/mipmap-anydpi-v26/ic_launcher.xml").read_text(encoding="utf-8")
    round_launcher = (root / "src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml").read_text(encoding="utf-8")
    if launcher != round_launcher or "@drawable/nanfeng_ai_icon_background" not in launcher or "@drawable/nanfeng_ai_icon_foreground" not in launcher:
        raise ValueError("adaptive launcher and round launcher must use the same two layers")
    foreground = root / "src/main/res/drawable-nodpi/nanfeng_ai_icon_foreground_image.png"
    width, height, _, _ = read_png(foreground)
    if (width, height) != (432, 432):
        raise ValueError(f"Android foreground must be 432x432, got {width}x{height}")
    desktop_root = args.desktop_root
    desktop_rgba = desktop_root / "icons/nanfeng_ai_icon_rgba.png"
    require_file(desktop_root, "icons/nanfeng_ai_icon_rgba.png")
    desktop_width, desktop_height, desktop_channels, _ = read_png(desktop_rgba)
    if (desktop_width, desktop_height, desktop_channels) != (1024, 1024, 4):
        raise ValueError(f"Desktop RGBA must be 1024x1024 RGBA, got {desktop_width}x{desktop_height} channels={desktop_channels}")
    desktop_runtime = desktop_root / "icons/icon.png"
    require_file(desktop_root, "icons/icon.png")
    runtime_width, runtime_height, runtime_channels, _ = read_png(desktop_runtime)
    if (runtime_width, runtime_height, runtime_channels) != (1024, 1024, 4):
        raise ValueError(f"Desktop runtime icon must be 1024x1024 RGBA, got {runtime_width}x{runtime_height} channels={runtime_channels}")
    require_file(desktop_root, "icons/nanfeng_ai_icon.icns")
    desktop_config = (desktop_root / "tauri.conf.json").read_text(encoding="utf-8")
    if '"icons/nanfeng_ai_icon.icns"' not in desktop_config:
        raise ValueError("Tauri bundle must point to the Desktop ICNS launcher asset")
    print(f"PASS source={args.source.name} sha256={sha256(args.source)} bbox={source[:4]}")
    print(f"PASS candidate={args.candidate.name} sha256={sha256(args.candidate)} bbox={candidate[:4]} scale={ratio_w:.4f}x/{ratio_h:.4f}x")
    print(f"PASS android_foreground={sha256(foreground)} dimensions=432x432 adaptive=shared")
    print(f"PASS desktop_rgba={sha256(desktop_rgba)} dimensions=1024x1024 rgba=master-derived")
    print(f"PASS desktop_runtime_png={sha256(desktop_runtime)} dimensions=1024x1024 rgba=master-derived")
    print(f"PASS desktop_icns={sha256(desktop_root / 'icons/nanfeng_ai_icon.icns')} tauri=linked legacy=all-densities")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, ValueError, zlib.error) as error:
        print(f"FAIL {error}", file=sys.stderr)
        raise SystemExit(1)
